name: Publish
on: [workflow_dispatch]

jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Publish
          with:
            APIKEY: ${{ secrets.PSGALLERYAPIKEY }}
          run: .\Publish.ps1
          shell: pwsh
